### ISSUE TITLE
Token consumption issue in API calls by DeviseSqreener#Sqreen?

### ISSUE THREAD

**Issue by colinxfleming** [sqreen/devise_sqreener#3]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
Hey, let me first say thanks -- Sqreen is a wonderful service that helps me sleep better at night and I am very grateful for the work you all have put into it.

I've spent some time trying to rig `devise_sqreener` for some extra coverage on a project I maintain that's covered by service-level sqreen, and I'm having a little bit of difficulty. I apologize if this is a just me thing! It seems like either the API calls made by `DeviseSqreener#Sqreen` are either dropping the token or expecting something else than I'm giving it, and I can't quite figure out why. Steps to reproduce and a minimal reproduction app are included.

#### Reproducible in:
devise_sqreener version: 0.1.1
Rails version: 5.1
Ruby version: 2.4.3 (though also getting this failure on 2.5.1)
OS version(s): Mac OS High Sierra 10.13.4

#### Steps to reproduce:

0. Create a new sqreen app, application environment development, and get the API key
1. Clone https://github.com/colinxfleming/sqreencheck , a minimal reproduction I made that sets up devise and devise_sqreener
2. `$ bundle install`
3. `$ export SQREEN_API_TOKEN=YOUR_TOKEN_HERE` with the token from the new sqreen app you've set up
4. `$ rails c`

At this point, we confirm that the token is properly loaded into the Sqreener class:
1. `User.class.sqreener  #=> #<DeviseSqreener::Sqreen:0x00007fde292cbc58 @sqreen_api_token="YOUR_TOKEN_HERE">`

And we try to make the call -- I think this is basically what happens on login or user create --
1. `User.sqreener.sqreen_email('c3flemin@gmail.com')`

### Expected result:
Based on the docs, I think I'm expecting a hash of the data back, since I'm making a request with the library containing an API token.

### Actual result:
Request response was a 401 so it returned `nil`. The response body is as follows, which seems to indicate that either the token is getting dropped somehow, the token is bad for reasons I can't quite determine, or the API is expecting a different token than I think it does.

```
"{\"code\":401,\"details\":null,\"errno\":4011,\"error\":\"Unauthorized\",\"info\":null,\"message\":\"No key was found in this request. You can retrieve your free API key at https://www.sqreen.io/developers\"}\n" 
```

### Attachments:
https://github.com/colinxfleming/sqreencheck

Thanks very much for your time, and let me know if there's anything I can do to be helpful (or if I'm doing something silly by accident, in which case, sorry about that!)

**Comment by aviat** [comment]
Hello @colinxfleming , we've decided to sunset this API as we were not happy with the relevance of some data we provided. Plus, it was not aligned with our product roadmap. We may come back to it at later stages if our customers request such a feature.
Let me know if I can help you further!

**Comment by colinxfleming** [comment]
Copy that -- thanks very much for the quick response @aviat . I'll close this issue as a wontfix here. Thanks much!
